apiVersion: v1
kind: Pod
metadata:
  name: execfuse-jinja
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

    - name: inferno
      image: dievri/9p-execfuse-jinja2:master
      imagePullPolicy: Always
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
      volumeMounts:
        - name: shared-data
          mountPath: /execfuse-fs
        - name: devfuse
          mountPath: /dev/fuse
  
  initContainers:
    - name: execfuse-jinja2
      image: dievri/execfuse-jinja2:master
      imagePullPolicy: Always
      volumeMounts:
        - name: shared-data
          mountPath: /execfuse-fs
        - name: config-volume
          mountPath: /execfuse-jinja2/examples/fs.yml
          subPath: fs.yml
      command: ["/bin/sh"]
      args: ["-c", "cd /execfuse-jinja2 && jinja2 examples/fs.yml | ./wrapper.sh fs | tar xvf - -C /execfuse-fs --strip 1"]

  volumes:
    - name: config-volume
      configMap: 
        name: execfuse-j2-definition
    - name: shared-data
      emptyDir: {}
    - name: devfuse
      hostPath:
        path: /dev/fuse
