apiVersion: v1
kind: Pod
metadata:
  name: execfuse-jinja
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: inferno
    image: dievri/9p-execfuse-jinja2:master
    volumeMounts:
    - name: shared-data
      mountPath: /execfuse-fs

  - name: execfuse-jinja2
    image: dievri/execfuse-jinja2:master
    volumeMounts:
      - name: shared-data
        mountPath: /execfuse-fs
      - name: config-volume
        mountPath: /tmp/fs.yml
        subPath: fs.yml
    command: ["/bin/sh"]
    args: ["-c", "jinja2 /tmp/fs.yml | wrapper.sh fs | tar xcvf - -C /execfuse-fs"]
  volumes:
    - name: config-volume
      configMap: 
        name: execfuse-j2-definition
    - name: shared-data
      emptyDir: {}
