#!/bin/sh
{% set fs_op = self._TemplateReference__context.name %}
{% include 'common.j2' %}
{% import 'util.j2' as util %}
set -e
cd ${HOME_TMP}
export DIR_NAME=$1

{% include 'cache.j2' %}

cat > $CACHE_FILE_NAME

{% macro tree(parent_path, fs, parent_fs) %}

  {% if fs is mapping and parent_fs is not none %}
    {% set dummy=fs.__setitem__("__parent", parent_fs.copy()) %}
  {% endif %}

  {%- for path in fs -%}
    {# skip virtual parent ref #}
    {%- if path == "__parent" -%}
      {% continue %} 
    {% endif %} {# if path == "__parent" #}
    {% if path != fs_op and path[:1] == "/" %} 
      {{ tree(parent_path + "/" + path if (parent_path != "/") else path, fs[path], fs) }} 
      {% continue %}
    {% endif %} {# if path != fs_op #}
  {% endfor %}
  if (path ~ /^{{ parent_path | regex_replace("//", "/", "g") | regex_replace("/", "\/", "g") }}$/) {
  {% if fs_op in fs %}

    path_lvl=NF
    {{ util.tree_up(fs, "sh") }}

    {%- if "sh" in fs[fs_op] %}
      {% set handler = fs[fs_op]["sh"] %}
    printf("echo {{ handler | b64encode }} | base64 -d\n")
    {%- endif %}
  {% endif %} {# if fs_op in fs #}
  } 
{%- endmacro %}

{% include 'fs_awk_loop.j2' %}
